### ISSUE TITLE
Ambiguity in Output Measurement Description

### ISSUE THREAD

**Issue by zachvpeirce** [MarquisdeGeek/us_ruler#1]
I encountered an issue with the output provided by the project, which is causing significant confusion and ambiguity, particularly as someone based in the United States. The output given for a 2-meter input was:

`"It is very slightly longer than the diameter of 9 size 5 regulation footballs."
`

This description is problematic because I am unsure if I should measure the football pointy end to pointy end or along the round side. 

Steps to Reproduce:

1. Input the value 2 m into the system.
2. Observe the output provided.

Expected Behavior:
The output should be clear and universally understandable. 

Actual Behavior:
The output provided is ambiguous and can be misinterpreted, leading to potential errors in application.

Proposed Solution:
To address this issue, I suggest the following improvements:
- Update the ball to a "soccer" ball to avoid ambiguity
- Even better, rely on images in case the words are too confusing so include the ⚽ emoji for clarity. 

Additional Context:
Given the critical nature of precise measurements in engineering and other technical fields, it is important to provide outputs that are clear, unambiguous, and easily interpretable by users from all backgrounds.

Thank you for considering this issue. I am available to provide further details or clarification if needed.

**Comment by MarquisdeGeek** [comment]
https://github.com/MarquisdeGeek/us_ruler/pull/3
